### PR TITLE
Sync master with release-4.11 branch

### PR DESCRIPTION
**Pull request by praveenkumar**
Now 4.11 is released and we are start consuming it so better to have our master branch sync with 4.11 branch now and we will create release-4.12 branch for dev purpose (mostly accommodate changes which doesn't affect our master)

### CODE REVIEW

**Comment by gbraad** [comment]
I am not so convinced these branches really add much value. What am I missing?

**Comment by praveenkumar** [comment]
> > have our master branch sync with 4.11 branch
> 
> You mean, as indicated from the "release-4.11 -> master" at the top that this is actually syncing master with 4.11 and not master sync with 4.11

@gbraad `18 commits into [master](https://github.com/code-ready/snc) from [release-4.11](https://github.com/code-ready/snc/tree/release-4.11)` so yes we are making sure now that master become release-4.11.

**Comment by cfergeau** [comment]
Fwiw, I did not expect to see that many commits in release-4.11 which are not in master, I thought most of the work was done in master, and cherry-picked to 4.11 when needed.

**Review by cfergeau — APPROVED** [review]

**Comment by praveenkumar** [comment]
/close 

because of #568, looks like I did rebase wrong.

**Comment by gbraad** [comment]
Ooohhh I hope so.
As the amount of commits made me worried too. Hence the questiion and almost questioning the nature of these branches.

**Pull request closed without merging**
