### PR TITLE
Add node debug image to cache

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch is going to cache the image which is used for oc debug node
so the user don't have to depend on the internet bandwidth in case try
to debug the node.

```
$ oc version
Client Version: 4.7.1
Server Version: 4.7.1
Kubernetes Version: v1.20.0+5fbfd19

$ oc get events
LAST SEEN   TYPE     REASON    OBJECT                         MESSAGE
42s         Normal   Pulling   pod/crc-m7q2f-master-0-debug   Pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1e15a871ce436a7db937391697d4bfdf1d8823ea0a822f626d9e8c3a74d60d62"

$ curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.1/release.txt | grep "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1e15a871ce436a7db937391697d4bfdf1d8823ea0a822f626d9e8c3a74d60d62"
  tools                                          quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1e15a871ce436a7db937391697d4bfdf1d8823ea0a822f626d9e8c3a74d60d62
```

### CODE REVIEW

**Comment by cfergeau** [comment]
What is the impact on bundle size, if any?

**Comment by praveenkumar** [comment]
> What is the impact on bundle size, if any?

Didn't tested yet, let's CI do it for us :)

**Comment by praveenkumar** [comment]
@cfergeau I don't see any increase in the bundle size, check the https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/code-ready_snc/360/pull-ci-code-ready-snc-master-e2e-snc/1370290049043664896 (artifacts) which is part of #360

**Comment by cfergeau** [comment]
The #360 bundle is 100MB bigger than the one generated in this PR, does not look like we can easily compare sizes from these 2 PRs.

**Comment by cfergeau** [comment]
Looking at the logs:
```
++ ./openshift-clients/linux/oc --kubeconfig=crc-tmp-install-data/auth/kubeconfig adm release info --image-for=tools
+ tool_image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bf47a5107539f27c77d16c9d5664837d8ff2e3015424328aaf0988e786ebff44
+ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_ecdsa_crc core@api.crc.testing -- sudo crictl pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bf47a5107539f27c77d16c9d5664837d8ff2e3015424328aaf0988e786ebff44
Warning: Permanently added 'api.crc.testing,192.168.126.11' (ECDSA) to the list of known hosts.
Image is up to date for quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bf47a5107539f27c77d16c9d5664837d8ff2e3015424328aaf0988e786ebff44
```

The image is apparently already present in our bundle.

**Comment by cfergeau** [comment]
Looking at free disk space before/after pulling the debug image, there is a 300MB difference. I'd be really interested in comparing bundle sizes with/without this change given this additional disk use.

**Comment by praveenkumar** [comment]
Since there is only supported way to use disconnect is by using mirror registry so even we cache this image might not solve user dependency over network or mirror registry. It is hard to know what all the images from core component user is trying to use/consume.

closing this one.

**Pull request closed without merging**
