### PR TITLE
Cherry-picks from the master to release-4.13 branch

### PR DESCRIPTION
**Pull request by praveenkumar**
Following Pr will not need after merge
-  #669 
- #670

### CODE REVIEW

**Comment by cfergeau** [comment]
Are there commits from master that are unwanted in the 4.13 branch? If not, I'd go with a merge.

**Comment by praveenkumar** [comment]
> Are there commits from master that are unwanted in the 4.13 branch? 

@cfergeau no, actually we just need to adjust one commit for microshift.sh side to change the release branch for 4.13, except that everything is just cherry-picked. 
- https://github.com/crc-org/snc/pull/669#discussion_r1138442851

**Comment by cfergeau** [comment]
> > Are there commits from master that are unwanted in the 4.13 branch?
> 
> @cfergeau no, actually we just need to adjust one commit for microshift.sh side to change the release branch for 4.13, except that everything is just cherry-picked.
> 
>     * [[release-4.13] Initial bits to create Microshift bundle #669 (comment)](https://github.com/crc-org/snc/pull/669#discussion_r1138442851)

Wouldn't a merge be better then to ensure we are not missing anything?

**Comment by praveenkumar** [comment]
>  Wouldn't a merge be better then to ensure we are not missing anything?

you mean merge and then amend that respective commit?

**Comment by cfergeau** [comment]
> > Wouldn't a merge be better then to ensure we are not missing anything?
> 
> you mean merge and then amend that respective commit?

We'd add another commit on top after the merge. Just a suggestion though.

**Comment by cfergeau** [comment]
> actually we just need to adjust one commit for microshift.sh side to change the release branch for 4.13, except that everything is just cherry-picked.

if you changed a commit, this is no longer a cherry-pick. And this makes the review more complicated, especially if this is not mentioned at all in the PR description.

**Comment by praveenkumar** [comment]
if we merge master on top of release-4.13 branch it will have conflicts and git history contain the merge message. following I tried and commit history doesn't look good.
```
$ git checkout -b merge_4.13_changes origin/release-4.13
$ git merge master 
```

 currently changes are part of https://github.com/crc-org/snc/compare/release-4.13...praveenkumar:merge_4.13_changes?expand=1

**Comment by praveenkumar** [comment]
With internal discussion on slack, I am going with current cherry-picks. In future cherry-picks (which are manual) need to have reason if a commit is amended during cherry-pick to track and fast review as part of PR description.

**Comment by cfergeau** [comment]
> With internal discussion on slack, I am going with current cherry-picks.

I must have missed the discussion where it was decided that this PR would be merged with no further review. I did not even get to the "review" part of the PR since the initial description was lacking details.

**Pull request merged**
