### PR TITLE
Create systemd unit for dnsmasq container

### PR DESCRIPTION
**Pull request by praveenkumar**
It would help to run the dnsmasq container in case there is a reboot.

### CODE REVIEW

**Review by gbraad — APPROVED** [review]

**Comment by guillaumerose** [comment]
This container is not needed with user network mode. Perhaps we can only keep this for linux bundle?

**Comment by praveenkumar** [comment]
> This container is not needed with user network mode. Perhaps we can only keep this for linux bundle?

@guillaumerose This need to be part of disk image not with the bundle and as of now we dont' have a way to separate those out different disk image for different platform. We consumed same disk image for every platform.

**Comment by guillaumerose** [comment]
It doesn't hurt to have this service. It is lightweight enough. No worry 👍

**Comment by praveenkumar** [comment]
@guillaumerose we are not going to enable/start this service on windows/mac it is part of the image but just inactive.

**Pull request merged**
